const WORD_BANK = {
  jp: [
    { kanji: '猫', kana: 'ねこ' },
    { kanji: '犬', kana: 'いぬ' },
    { kanji: '桜', kana: 'さくら' },
    { kanji: '学校', kana: 'がっこう' },
    { kanji: '図書館', kana: 'としょかん' },
    { kanji: '新幹線', kana: 'しんかんせん' },
    { kanji: '冒険', kana: 'ぼうけん' },
    { kanji: '魔法', kana: 'まほう' },
    { kanji: '勇者', kana: 'ゆうしゃ' },
    { kanji: '宝箱', kana: 'たからばこ' },
    { kanji: '蝶々', kana: 'ちょうちょう' },
    { kanji: '焼肉', kana: 'やきにく' },
    { kanji: '給料', kana: 'きゅうりょう' },
    { kanji: '掃除機', kana: 'そうじき' },
    { kanji: '珈琲', kana: 'こーひー' },
    { kanji: '東京', kana: 'とうきょう' },
    { kanji: '切符', kana: 'きっぷ' },
    { kanji: '散歩', kana: 'さんぽ' },
    { kanji: '温泉', kana: 'おんせん' },
    { kanji: '花火', kana: 'はなび' },
    { kanji: '恐竜', kana: 'きょうりゅう' },
    { kanji: '弟子', kana: 'でし' },
    { kanji: '雑誌', kana: 'ざっし' },
    { kanji: '写真', kana: 'しゃしん' },
    { kanji: '剣士', kana: 'けんし' },
    { kanji: '魔王', kana: 'まおう' },
    { kanji: '回復魔法', kana: 'かいふくまほう' },
    { kanji: '経験値', kana: 'けいけんち' },
    { kanji: '装備', kana: 'そうび' },
    { kanji: '盾', kana: 'たて' },
    { kanji: '弓矢', kana: 'ゆみや' },
    { kanji: '杖', kana: 'つえ' },
    { kanji: '鎧', kana: 'よろい' },
    { kanji: '回復薬', kana: 'かいふくやく' },
    { kanji: '毒消し', kana: 'どくけし' },
    { kanji: '復活', kana: 'ふっかつ' },
    { kanji: '冒険者', kana: 'ぼうけんしゃ' },
    { kanji: '呪文書', kana: 'じゅもんしょ' },
    { kanji: '洞窟', kana: 'どうくつ' },
    { kanji: '古代遺跡', kana: 'こだいいせき' },
    { kanji: '伝説', kana: 'でんせつ' },
    { kanji: '女神', kana: 'めがみ' },
    { kanji: '聖水', kana: 'せいすい' },
    { kanji: '指輪', kana: 'ゆびわ' },
    { kanji: '強敵', kana: 'きょうてき' },
    { kanji: '討伐', kana: 'とうばつ' },
    { kanji: '城壁', kana: 'じょうへき' },
    { kanji: '騎士', kana: 'きし' },
    { kanji: '魔術師', kana: 'まじゅつし' },
    { kanji: '精霊', kana: 'せいれい' },
    { kanji: '勇気', kana: 'ゆうき' },
    { kanji: '絆', kana: 'きずな' },
    { kanji: '覚醒', kana: 'かくせい' },
    { kanji: '会心の一撃', kana: 'かいしんのいちげき' },
    { kanji: '財布', kana: 'さいふ' },
    { kanji: '傘', kana: 'かさ' },
    { kanji: '眼鏡', kana: 'めがね' },
    { kanji: '自転車', kana: 'じてんしゃ' },
    { kanji: '電車', kana: 'でんしゃ' },
    { kanji: '飛行機', kana: 'ひこうき' },
    { kanji: '病院', kana: 'びょういん' },
    { kanji: '公園', kana: 'こうえん' },
    { kanji: '神社', kana: 'じんじゃ' },
    { kanji: '花束', kana: 'はなたば' },
    { kanji: '誕生日', kana: 'たんじょうび' },
    { kanji: '運動会', kana: 'うんどうかい' },
    { kanji: '遠足', kana: 'えんそく' },
    { kanji: '台風', kana: 'たいふう' },
    { kanji: '雪だるま', kana: 'ゆきだるま' },
    { kanji: '財産', kana: 'ざいさん' },
    { kanji: '洗濯機', kana: 'せんたくき' },
    { kanji: '冷蔵庫', kana: 'れいぞうこ' },
    { kanji: '炊飯器', kana: 'すいはんき' },
    { kanji: '目覚まし', kana: 'めざまし' },
    { kanji: '定食屋', kana: 'ていしょくや' },
    { kanji: '居酒屋', kana: 'いざかや' },
    { kanji: '商店街', kana: 'しょうてんがい' },
    { kanji: '空港', kana: 'くうこう' },
    { kanji: '灯台', kana: 'とうだい' },
    { kanji: '波止場', kana: 'はとば' },
    { kanji: '漁師', kana: 'りょうし' },
    { kanji: '農家', kana: 'のうか' },
    { kanji: '田植え', kana: 'たうえ' },
    { kanji: '竜巻', kana: 'たつまき' },
    { kanji: '隕石', kana: 'いんせき' },
    { kanji: '迷宮', kana: 'めいきゅう' },
    { kanji: '秘宝', kana: 'ひほう' },
    { kanji: '呪い', kana: 'のろい' },
    { kanji: '魔物', kana: 'まもの' },
    { kanji: '竜王', kana: 'りゅうおう' },
    { kanji: '聖剣', kana: 'せいけん' },
    { kanji: '魔剣', kana: 'まけん' },
    { kanji: '邪神', kana: 'じゃしん' },
    { kanji: '賢者', kana: 'けんじゃ' },
    { kanji: '大魔導士', kana: 'だいまどうし' },
    { kanji: '竜騎士', kana: 'りゅうきし' },
    { kanji: '守護神', kana: 'しゅごしん' },
    { kanji: '封印', kana: 'ふういん' },
    { kanji: '覚者', kana: 'かくしゃ' },
    { kanji: '転生', kana: 'てんせい' },
    { kanji: '加護', kana: 'かご' },
    { kanji: '天啓', kana: 'てんけい' },
    { kanji: '竜脈', kana: 'りゅうみゃく' },
    { kanji: '星屑', kana: 'ほしくず' },
    { kanji: '流星群', kana: 'りゅうせいぐん' },
    { kanji: '満月', kana: 'まんげつ' },
    { kanji: '蒼穹', kana: 'そうきゅう' },
    { kanji: 'パーティー', kana: 'ぱーてぃー' },
    { kanji: '仲間', kana: 'なかま' },
    { kanji: '敵', kana: 'てき' },
    { kanji: '味方', kana: 'みかた' },
    { kanji: '攻撃', kana: 'こうげき' },
    { kanji: '防御', kana: 'ぼうぎょ' },
    { kanji: '回避', kana: 'かいひ' },
    { kanji: '必殺技', kana: 'ひっさつわざ' },
    { kanji: '奥義', kana: 'おうぎ' },
    { kanji: '秘技', kana: 'ひぎ' },
    { kanji: '魔力', kana: 'まりょく' },
    { kanji: '体力', kana: 'たいりょく' },
    { kanji: '気力', kana: 'きりょく' },
    { kanji: '状態異常', kana: 'じょうたいいじょう' },
    { kanji: '麻痺', kana: 'まひ' },
    { kanji: '混乱', kana: 'こんらん' },
    { kanji: '石化', kana: 'せきか' },
    { kanji: '即死', kana: 'そくし' },
    { kanji: '全滅', kana: 'ぜんめつ' },
    { kanji: '強化', kana: 'きょうか' },
    { kanji: '弱体化', kana: 'じゃくたいか' },
    { kanji: '属性', kana: 'ぞくせい' },
    { kanji: '弱点', kana: 'じゃくてん' },
    { kanji: '耐性', kana: 'たいせい' },
    { kanji: '武器屋', kana: 'ぶきや' },
    { kanji: '防具屋', kana: 'ぼうぐや' },
    { kanji: '道具屋', kana: 'どうぐや' },
    { kanji: '教会', kana: 'きょうかい' },
    { kanji: '商人', kana: 'しょうにん' },
    { kanji: '鍛冶屋', kana: 'かじや' },
    { kanji: '錬金術師', kana: 'れんきんじゅつし' },
    { kanji: '吟遊詩人', kana: 'ぎんゆうしじん' },
    { kanji: '盗賊', kana: 'とうぞく' },
    { kanji: '暗殺者', kana: 'あんさつしゃ' },
    { kanji: '聖騎士', kana: 'せいきし' },
    { kanji: 'モンスター', kana: 'もんすたー' },
    { kanji: 'ドラゴン', kana: 'どらごん' },
    { kanji: 'ゴブリン', kana: 'ごぶりん' },
    { kanji: 'スライム', kana: 'すらいむ' },
    { kanji: 'ゾンビ', kana: 'ぞんび' },
    { kanji: '骸骨', kana: 'がいこつ' },
    { kanji: '魔王軍', kana: 'まおうぐん' },
    { kanji: '四天王', kana: 'してんのう' },
    { kanji: '王国', kana: 'おうこく' },
    { kanji: '城下町', kana: 'じょうかまち' },
    { kanji: '辺境', kana: 'へんきょう' },
    { kanji: '聖地', kana: 'せいち' },
    { kanji: '神殿', kana: 'しんでん' },
    { kanji: '結界', kana: 'けっかい' },
    { kanji: '称号', kana: 'しょうごう' },
  ],
  en: [
    'dragon', 'sword', 'castle', 'forest', 'magic', 'hero', 'quest', 'shield',
    'treasure', 'potion', 'village', 'wizard', 'battle', 'journey', 'legend',
    'phoenix', 'knight', 'crystal', 'portal', 'rescue', 'goblin', 'compass',
    'lantern', 'kingdom', 'blade', 'sorcerer', 'curse', 'guardian', 'warrior',
    'mercenary', 'oracle', 'relic', 'citadel', 'wraith', 'paladin', 'amulet',
    'catacomb', 'siege', 'rampart', 'chieftain',
  ],
};

const SENTENCE_BANK = {
  jp: [
    { kanji: '今日はとても良い天気ですね', kana: 'きょうはとてもよいてんきですね' },
    { kanji: '猫が窓の外を眺めています', kana: 'ねこがまどのそとをながめています' },
    { kanji: '冒険者たちは森の奥へ向かった', kana: 'ぼうけんしゃたちはもりのおくへむかった' },
    { kanji: '新しい魔法を覚えると強くなる', kana: 'あたらしいまほうをおぼえるとつよくなる' },
    { kanji: '駅前のカフェでコーヒーを飲んだ', kana: 'えきまえのかふぇでこーひーをのんだ' },
    { kanji: '毎日少しずつ練習すれば必ず上達する', kana: 'まいにちすこしずつれんしゅうすればかならずじょうたつする' },
    { kanji: '勇者は宝箱を開けて剣を手に入れた', kana: 'ゆうしゃはたからばこをあけてけんをてにいれた' },
    { kanji: 'しかし攻撃は外れてしまった！', kana: 'しかしこうげきははずれてしまった！' },
    { kanji: '世界の半分をくれてやろう', kana: 'せかいのはんぶんをくれてやろう' },
    { kanji: '会心の一撃が敵に炸裂した！', kana: 'かいしんのいちげきがてきにさくれつした！' },
    { kanji: '目の前に恐ろしい魔物が現れた', kana: 'めのまえにおそろしいまものがあらわれた' },
    { kanji: 'この先には強大な敵が待ち構えている', kana: 'このさきにはきょうだいなてきがまちかまえている' },
    { kanji: '勇者は仲間を信じて剣を抜いた', kana: 'ゆうしゃはなかまをしんじてけんをぬいた' },
    { kanji: '体力が残りわずかだ、油断するな', kana: 'たいりょくがのこりわずかだ、ゆだんするな' },
    { kanji: 'ボスの咆哮が洞窟中に響き渡った', kana: 'ぼすのほうこうがどうくつじゅうにひびきわたった' },
    { kanji: '呪文が発動し、辺りは眩い光に包まれた', kana: 'じゅもんがはつどうし、あたりはまばゆいひかりにつつまれた' },
    { kanji: '逃げるか、それとも戦うか、選ぶのは君だ？', kana: 'にげるか、それともたたかうか、えらぶのはきみだ？' },
    { kanji: '宝箱からまばゆい光が溢れ出した', kana: 'たからばこからまばゆいひかりがあふれだした' },
    { kanji: '仲間が倒れた、今すぐ回復魔法を唱えろ！', kana: 'なかまがたおれた、いますぐかいふくまほうをとなえろ！' },
    { kanji: 'どうやらこの部屋には罠が仕掛けられているようだ', kana: 'どうやらこのへやにはわながしかけられているようだ' },
    { kanji: 'レベルが上がり、体中に力がみなぎるのを感じた', kana: 'れべるがあがり、からだじゅうにちからがみなぎるのをかんじた' },
    { kanji: '魔王の城はここから遠くはない', kana: 'まおうのしろはここからとおくはない' },
    { kanji: '目覚めよ、選ばれし者よ', kana: 'めざめよ、えらばれしものよ' },
    { kanji: '冒険の書にはまだ何も記されていない', kana: 'ぼうけんのしょにはまだなにもしるされていない' },
    { kanji: 'パーティーの誰かが毒を受けている', kana: 'ぱーてぃーのだれかがどくをうけている' },
    { kanji: '敵は突然、姿を消した', kana: 'てきはとつぜん、すがたをけした' },
    { kanji: '古びた地図には宝の在り処が記されていた', kana: 'ふるびたちずにはたからのありかがしるされていた' },
    { kanji: '扉の向こうから低い唸り声が聞こえる', kana: 'とびらのむこうからひくいうなりごえがきこえる' },
    { kanji: '全滅かと思われたその時、光が差し込んだ', kana: 'ぜんめつかとおもわれたそのとき、ひかりがさしこんだ' },
    { kanji: '装備を整えてから先へ進もう', kana: 'そうびをととのえてからさきへすすもう' },
    { kanji: 'まもなくボス部屋に到達する', kana: 'まもなくぼすべやにとうたつする' },
    { kanji: '経験値が入り、パーティー全体が成長した', kana: 'けいけんちがはいり、ぱーてぃーぜんたいがせいちょうした' },
    { kanji: '呪われたアイテムを装備してしまったようだ', kana: 'のろわれたあいてむをそうびしてしまったようだ' },
    { kanji: 'セーブポイントを見つけ、ひとまず安心する', kana: 'せーぶぽいんとをみつけ、ひとまずあんしんする' },
    { kanji: '敵の弱点属性を見極めろ', kana: 'てきのじゃくてんぞくせいをみきわめろ' },
    { kanji: 'ここから先はセーブができない', kana: 'ここからさきはせーぶができない' },
    { kanji: '隠し通路を発見した', kana: 'かくしつうろをはっけんした' },
    { kanji: '味方が裏切り者だったなんて', kana: 'みかたがうらぎりものだったなんて' },
    { kanji: '王からの依頼を受けることにした', kana: 'おうからのいらいをうけることにした' },
    { kanji: '深淵の底で何かが目を覚ました', kana: 'しんえんのそこでなにかがめをさました' },
    { kanji: 'あと一歩で必殺技が発動する', kana: 'あといっぽでひっさつわざがはつどうする' },
    { kanji: '疲労がたまり、動きが鈍くなってきた', kana: 'ひろうがたまり、うごきがにぶくなってきた' },
    { kanji: '仲間の絆が新たな力を呼び覚ました', kana: 'なかまのきずながあらたなちからをよびさました' },
    { kanji: '霧の中から足音が近づいてくる', kana: 'きりのなかからあしおとがちかづいてくる' },
    { kanji: '古代文明の遺産がここに眠っている', kana: 'こだいぶんめいのいさんがここにねむっている' },
    { kanji: '運命の分かれ道に差し掛かった', kana: 'うんめいのわかれみちにさしかかった' },
    { kanji: '勝利の女神が微笑んでいるようだ', kana: 'しょうりのめがみがほほえんでいるようだ' },
    { kanji: '冷たい風が洞窟の奥から吹き抜けていく', kana: 'つめたいかぜがどうくつのおくからふきぬけていく' },
    { kanji: '誰かが助けを求めているようだ', kana: 'だれかがたすけをもとめているようだ' },
    { kanji: 'この扉には鍵が必要らしい', kana: 'このとびらにはかぎがひつようらしい' },
    { kanji: '剣先が淡く光り始めた', kana: 'けんさきがあわくひかりはじめた' },
    { kanji: '敵の攻撃パターンを読み切った', kana: 'てきのこうげきぱたーんをよみきった' },
    { kanji: 'まだ見ぬ強敵が待っているに違いない', kana: 'まだみぬきょうてきがまっているにちがいない' },
    { kanji: '仲間の回復が間に合った', kana: 'なかまのかいふくがまにあった' },
    { kanji: '遠くで鐘の音が鳴り響いている', kana: 'とおくでかねのねがなりひびいている' },
    { kanji: '冒険はまだ始まったばかりだ', kana: 'ぼうけんはまだはじまったばかりだ' },
    { kanji: '光の剣が闇を切り裂いた', kana: 'ひかりのけんがやみをきりさいた' },
    { kanji: 'ここに来るまでの道のりは長かった', kana: 'ここにくるまでのみちのりはながかった' },
    { kanji: '次の街まではまだ距離がある', kana: 'つぎのまちまではまだきょりがある' },
    { kanji: '不思議な力が体の奥から湧き上がる', kana: 'ふしぎなちからがからだのおくからわきあがる' },
    { kanji: '敵将を討ち取れば戦況は変わるはずだ', kana: 'てきしょうをうちとればせんきょうはかわるはずだ' },
    { kanji: '静寂の中、剣を構え直す', kana: 'せいじゃくのなか、けんをかまえなおす' },
    { kanji: '誰も足を踏み入れたことのない領域だ', kana: 'だれもあしをふみいれたことのないりょういきだ' },
    { kanji: '宿屋で一晩休むことにした', kana: 'やどやでひとばんやすむことにした' },
    { kanji: '商人から貴重な情報を得た', kana: 'しょうにんからきちょうなじょうほうをえた' },
    { kanji: '目の前の道が二つに分かれている', kana: 'めのまえのみちがふたつにわかれている' },
    { kanji: '最後の力を振り絞る時が来た', kana: 'さいごのちからをふりしぼるときがきた' },
    { kanji: '今夜は星がとても綺麗に見える', kana: 'こんやはほしがとてもきれいにみえる' },
    { kanji: '隣の部屋から物音が聞こえた', kana: 'となりのへやからものおとがきこえた' },
    { kanji: '明日の天気予報は雨のようだ', kana: 'あしたのてんきよほうはあめのようだ' },
    { kanji: '駅までは歩いて十五分ほどかかる', kana: 'えきまではあるいてじゅうごふんほどかかる' },
    { kanji: '母は毎朝早くから台所に立つ', kana: 'はははまいあさはやくからだいどころにたつ' },
    { kanji: '週末は久しぶりに映画を観に行った', kana: 'しゅうまつはひさしぶりにえいがをみにいった' },
    { kanji: '新しい靴を履いて出かけよう', kana: 'あたらしいくつをはいてでかけよう' },
    { kanji: '桜の花びらが風に舞っている', kana: 'さくらのはなびらがかぜにまっている' },
    { kanji: '夏休みの宿題がまだ終わっていない', kana: 'なつやすみのしゅくだいがまだおわっていない' },
    { kanji: '図書館で静かに本を読む時間が好きだ', kana: 'としょかんでしずかにほんをよむじかんがすきだ' },
    { kanji: '電車が遅れて会社に遅刻しそうだ', kana: 'でんしゃがおくれてかいしゃにちこくしそうだ' },
    { kanji: '隣町まで自転車で行くことにした', kana: 'となりまちまでじてんしゃでいくことにした' },
    { kanji: '台風が接近しているらしい', kana: 'たいふうがせっきんしているらしい' },
    { kanji: '久しぶりに実家に帰ることにした', kana: 'ひさしぶりにじっかにかえることにした' },
    { kanji: '朝ごはんはパンと卵にした', kana: 'あさごはんはぱんとたまごにした' },
    { kanji: '勇者の一行はついに魔王城へたどり着いた', kana: 'ゆうしゃのいっこうはついにまおうじょうへたどりついた' },
    { kanji: '古びた祠の奥に何かが眠っている気配がする', kana: 'ふるびたほこらのおくになにかがねむっているけはいがする' },
    { kanji: '剣を鞘に納め、静かに歩みを進める', kana: 'けんをさやにおさめ、しずかにあゆみをすすめる' },
    { kanji: '突如として地面が揺れ、亀裂が走った', kana: 'とつじょとしてじめんがゆれ、きれつがはしった' },
    { kanji: '仲間との絆が試される瞬間が訪れた', kana: 'なかまとのきずながためされるしゅんかんがおとずれた' },
    { kanji: '遠くの空に竜の影が見えた気がした', kana: 'とおくのそらにりゅうのかげがみえたきがした' },
    { kanji: '力を使い果たし、その場に膝をついた', kana: 'ちからをつかいはたし、そのばにひざをついた' },
    { kanji: '封印されし扉がゆっくりと開き始めた', kana: 'ふういんされしとびらがゆっくりとひらきはじめた' },
    { kanji: '敵の増援が到着する前に決着をつけろ', kana: 'てきのぞうえんがとうちゃくするまえにけっちゃくをつけろ' },
    { kanji: '魔力を練り上げ、必殺の一撃を放つ', kana: 'まりょくをねりあげ、ひっさつのいちげきをはなつ' },
    { kanji: '崩れゆく城の中で最後の戦いが始まった', kana: 'くずれゆくしろのなかでさいごのたたかいがはじまった' },
    { kanji: '遺跡の壁には見たことのない文字が刻まれていた', kana: 'いせきのかべにはみたことのないもじがきざまれていた' },
    { kanji: '一筋の光が暗闇を切り裂いていく', kana: 'ひとすじのひかりがくらやみをきりさいていく' },
    { kanji: '旅の途中で不思議な老人に出会った', kana: 'たびのとちゅうでふしぎなろうじんにであった' },
    { kanji: '剣と盾を構え、敵の出方を伺う', kana: 'けんとたてをかまえ、てきのでかたをうかがう' },
    { kanji: '湖のほとりで一夜を明かすことにした', kana: 'みずうみのほとりでいちやをあかすことにした' },
    { kanji: '遥か彼方から地鳴りのような音が響いた', kana: 'はるかかなたからじなりのようなおとがひびいた' },
    { kanji: '装備を新調し、次の戦いに備える', kana: 'そうびをしんちょうし、つぎのたたかいにそなえる' },
    { kanji: '仲間の一人が謎の病に倒れてしまった', kana: 'なかまのひとりがなぞのやまいにたおれてしまった' },
    { kanji: '竜の巣に足を踏み入れる勇気があるか', kana: 'りゅうのすにあしをふみいれるゆうきがあるか' },
    { kanji: '星々の導きに従い、旅路を進む', kana: 'ほしぼしのみちびきにしたがい、たびじをすすむ' },
    { kanji: '王都は思いのほか活気に満ちていた', kana: 'おうとはおもいのほかかっきにみちていた' },
    { kanji: '深い霧の向こうに古城が浮かび上がった', kana: 'ふかいきりのむこうにこじょうがうかびあがった' },
    { kanji: '敵の本拠地はこの山の奥にあるという', kana: 'てきのほんきょちはこのやまのおくにあるという' },
    { kanji: '最強の武器はまだこの世に眠っている', kana: 'さいきょうのぶきはまだこのよにねむっている' },
    { kanji: '傷ついた仲間を背負い、街を目指した', kana: 'きずついたなかまをせおい、まちをめざした' },
    { kanji: '静かな朝、鳥のさえずりで目が覚めた', kana: 'しずかなあさ、とりのさえずりでめがさめた' },
    { kanji: '商人は怪しげな微笑みを浮かべた', kana: 'しょうにんはあやしげなほほえみをうかべた' },
    { kanji: '廃墟と化した村に人影はなかった', kana: 'はいきょとかしたむらにひとかげはなかった' },
    { kanji: '見知らぬ紋章が刻まれた指輪を拾った', kana: 'みしらぬもんしょうがきざまれたゆびわをひろった' },
    { kanji: '森の奥に光る泉があると噂で聞いた', kana: 'もりのおくにひかるいずみがあるとうわさできいた' },
    { kanji: '一夜にして街の様子が一変していた', kana: 'いちやにしてまちのようすがいっぺんしていた' },
    { kanji: '最後の試練を乗り越えれば故郷に戻れる', kana: 'さいごのしれんをのりこえればこきょうにもどれる' },
    { kanji: '冷たい鎖に繋がれた囚人を見つけた', kana: 'つめたいくさりにつながれたしゅうじんをみつけた' },
    { kanji: '誰も語らぬ伝説が今、動き出す', kana: 'だれもかたらぬでんせつがいま、うごきだす' },
    { kanji: '鍛冶屋の主人は腕利きだと評判だった', kana: 'かじやのしゅじんはうでききだとひょうばんだった' },
    { kanji: '山道を抜けると小さな集落が見えてきた', kana: 'やまみちをぬけるとちいさなしゅうらくがみえてきた' },
    { kanji: '荒野に立つ一本の大樹が目印になった', kana: 'こうやにたついっぽんのたいじゅがめじるしになった' },
    { kanji: '深呼吸をして、扉に手をかけた', kana: 'しんこきゅうをして、とびらにてをかけた' },
    { kanji: '予期せぬ襲撃に一瞬、隊列が乱れた', kana: 'よきせぬしゅうげきにいっしゅん、たいれつがみだれた' },
    { kanji: '血の滲むような修行の日々が続いた', kana: 'ちのにじむようなしゅぎょうのひびがつづいた' },
    { kanji: '手にした地図はもうぼろぼろだった', kana: 'てにしたちずはもうぼろぼろだった' },
    { kanji: '誰かが見守ってくれている気がした', kana: 'だれかがみまもってくれているきがした' },
    { kanji: '満天の星の下、野営の準備を始めた', kana: 'まんてんのほしのした、やえいのじゅんびをはじめた' },
    { kanji: '敵将の首には莫大な懸賞金がかかっていた', kana: 'てきしょうのくびにはばくだいなけんしょうきんがかかっていた' },
    { kanji: '地下水路を伝って城へ侵入する計画だ', kana: 'ちかすいろをつたってしろへしんにゅうするけいかくだ' },
    { kanji: '最後の力で杖を掲げ、光の盾を展開した', kana: 'さいごのちからでつえをかかげ、ひかりのたてをてんかいした' },
    { kanji: '街の広場では祭りの準備が進んでいた', kana: 'まちのひろばではまつりのじゅんびがすすんでいた' },
    { kanji: '旧友との再会に思わず涙がこぼれた', kana: 'きゅうゆうとのさいかいにおもわずなみだがこぼれた' },
    { kanji: '未踏の大陸を目指し、船が出港した', kana: 'みとうのたいりくをめざし、ふねがしゅっこうした' },
    { kanji: '一撃で仕留めねば逆にやられてしまう', kana: 'いちげきでしとめねばぎゃくにやられてしまう' },
    { kanji: '長き旅の果てに、ついに答えが見えた', kana: 'ながきたびのはてに、ついにこたえがみえた' },
  ],
  en: [
    'The old wizard opened a portal to another world',
    'A brave knight rode through the dark forest at midnight',
    'The dragon guarded its treasure deep inside the mountain',
    'She picked up the glowing sword and felt its power',
    'Every legend begins with a single small step forward',
    'Practice a little every day and you will improve fast',
    'The village celebrated as the heroes returned home safely',
    'But the attack missed its mark!',
    'I shall grant you half of this world, the demon lord sneered',
    'A critical hit strikes the enemy!',
    'Your HP is running low, stay alert',
    'The boss let out a roar that shook the entire cave',
    'A hidden trap seems to guard this very room',
    'Level up! New strength surges through your body',
    'Retreat or fight, the choice is yours alone',
    'A fearsome monster blocks the path ahead',
    'Awaken, chosen one',
    'The adventure log has nothing written in it yet',
    'Someone in the party has been poisoned',
    'The enemy vanished without a trace',
    'An old map marks where the treasure lies',
    'A low growl echoes from beyond the door',
    'Just when all seemed lost, a light broke through',
    'Check your gear before pressing onward',
    'The boss chamber lies just ahead',
    'The whole party gained experience and grew stronger',
    'It seems you equipped a cursed item',
    'Finding a save point brings a moment of relief',
    'Identify the weakness before you strike',
    'There is no saving beyond this point',
    'A hidden passage has been discovered',
    'Could an ally really be the traitor',
    'Something stirred at the bottom of the abyss',
    'A cold wind blows from deep within the cave',
    'Someone seems to be calling for help',
    'This door appears to need a key',
    'The blade began to glow faintly',
    'You have read through the enemy\'s attack pattern',
    'A stronger foe must surely be waiting ahead',
    'The healing arrived just in time',
    'A distant bell echoes across the land',
    'The adventure has only just begun',
    'The sword of light cut through the darkness',
    'The road here has been long',
    'The next town is still far away',
    'A strange power wells up from within',
    'Defeat the enemy commander and the tide will turn',
    'In the silence, you ready your blade once more',
    'No one has ever set foot in this region before',
    'You decide to rest for the night at the inn',
    'A merchant shares valuable information',
    'The path ahead splits in two',
    'The time has come to give it everything you have',
  ],
};

const LONG_BANK = {
  jp: [
    {
      kanji: '昔々、あるところに小さな村がありました。その村には勇敢な少年が住んでいて、毎日剣の練習をしていました。ある日、森の奥から恐ろしい竜が現れたという噂が広がりました。少年は仲間たちと共に、村を守るための冒険に出発することを決意したのです。',
      kana: 'むかしむかし、あるところにちいさなむらがありました。そのむらにはゆうかんなしょうねんがすんでいて、まいにちけんのれんしゅうをしていました。あるひ、もりのおくからおそろしいりゅうがあらわれたといううわさがひろがりました。しょうねんはなかまたちとともに、むらをまもるためのぼうけんにしゅっぱつすることをけついしたのです。',
    },
    {
      kanji: '魔法学校に入学した少女は、最初は呪文がうまく使えず苦労していました。しかし毎日図書館に通って古い魔法書を読み続けるうちに、少しずつ自信をつけていきました。半年後、彼女は誰よりも上手に炎の魔法を操れるようになっていたのです。',
      kana: 'まほうがっこうににゅうがくしたしょうじょは、さいしょはじゅもんがうまくつかえずくろうしていました。しかしまいにちとしょかんにかよってふるいまほうしょをよみつづけるうちに、すこしずつじしんをつけていきました。はんとしご、かのじょはだれよりもじょうずにほのおのまほうをあやつれるようになっていたのです。',
    },
    {
      kanji: '世界の半分をくれてやろうと魔王は笑った。しかし勇者は臆することなく剣を構えた。次の瞬間、閃光と共に激しい斬り合いが始まった。しかし攻撃は外れてしまった！反撃を受け、勇者の体力は残りわずかとなる。それでも仲間たちの声援を受け、勇者は最後の力を振り絞り、渾身の一撃を魔王へと叩き込んだ。',
      kana: 'せかいのはんぶんをくれてやろうとまおうはわらった。しかしゆうしゃはおくすることなくけんをかまえた。つぎのしゅんかん、せんこうとともにはげしいきりあいがはじまった。しかしこうげきははずれてしまった！はんげきをうけ、ゆうしゃのたいりょくはのこりわずかとなる。それでもなかまたちのせいえんをうけ、ゆうしゃはさいごのちからをふりしぼり、こんしんのいちげきをまおうへとたたきこんだ。',
    },
  ],
  en: [
    'Long ago, in a kingdom surrounded by tall mountains, a young hero decided to leave home in search of adventure. The village elders warned her about the dangers hidden in the forest, but she was not afraid. With a small sword and a worn map, she set out at dawn, determined to find the ancient castle where a powerful treasure was said to be hidden. Along the way, she met a talking fox who offered to guide her through the darkest parts of the woods.',
    'The spaceship drifted quietly through the endless field of stars, its engines humming a low and steady song. Captain Rae checked the navigation panel one more time before turning to her crew. They had traveled for months searching for a new home, a planet where the air was clean and the soil could grow food again. As the ship approached an unknown blue planet, everyone gathered at the window, holding their breath, hoping this was finally the place they had been looking for.',
    'I shall grant you half of this world, the demon lord sneered, raising his blade. Yet the hero did not flinch, drawing his sword without hesitation. In an instant, a flash of light split the air and a fierce clash began. But the attack missed its mark! A counterstrike landed hard, and the hero\'s strength began to fade. Still, cheered on by his companions, the hero gathered his last ounce of power and drove one final blow into the demon lord.',
  ],
};

const SWORD_CATALOG = [
  { id: 'sword_bronze_k', name: '銅の剣', price: 800, statType: 'keystroke', value: 0.10 },
  { id: 'sword_iron_k', name: '鉄の剣', price: 3000, statType: 'keystroke', value: 0.20 },
  { id: 'sword_steel_k', name: '鋼の剣', price: 12000, statType: 'keystroke', value: 0.35 },
  { id: 'sword_magic_k', name: '魔法の剣', price: 45000, statType: 'keystroke', value: 0.55 },
  { id: 'sword_legend_k', name: '伝説の剣', price: 150000, statType: 'keystroke', value: 0.80 },
  { id: 'sword_training_w', name: '訓練用の剣', price: 800, statType: 'wordclear', value: 0.12 },
  { id: 'sword_sharp_w', name: '鋭利な剣', price: 3000, statType: 'wordclear', value: 0.24 },
  { id: 'sword_fang_w', name: '竜牙の剣', price: 12000, statType: 'wordclear', value: 0.42 },
  { id: 'sword_light_w', name: '光の剣', price: 45000, statType: 'wordclear', value: 0.66 },
  { id: 'sword_banish_w', name: '破邪の剣', price: 150000, statType: 'wordclear', value: 0.96 },
  { id: 'sword_rico', name: 'リコの剣', price: 10000000, statType: 'keystroke', value: 0.01, rico: true },
];

const SHIELD_CATALOG = [
  { id: 'shield_wood', name: '木の盾', price: 1000, expBonus: 0.10 },
  { id: 'shield_iron', name: '鉄の盾', price: 4000, expBonus: 0.20 },
  { id: 'shield_silver', name: '銀の盾', price: 15000, expBonus: 0.35 },
  { id: 'shield_goddess', name: '女神の盾', price: 50000, expBonus: 0.55 },
  { id: 'shield_holy', name: '聖なる盾', price: 160000, expBonus: 0.80 },
  { id: 'shield_rico', name: 'リコの盾', price: 10000000, expBonus: 0.01, rico: true },
];

const ARMOR_CATALOG = [
  { id: 'armor_cloth', name: '布の鎧', price: 0, comboStep: 20, comboSeconds: 2, capRatio: 0.5 },
  { id: 'armor_leather', name: '革の鎧', price: 1200, comboStep: 25, comboSeconds: 3, capRatio: 0.55 },
  { id: 'armor_chain', name: '鎖帷子', price: 5000, comboStep: 32, comboSeconds: 4, capRatio: 0.6 },
  { id: 'armor_steel', name: '鋼鉄の鎧', price: 18000, comboStep: 40, comboSeconds: 6, capRatio: 0.7 },
  { id: 'armor_dragon', name: '竜鱗の鎧', price: 60000, comboStep: 50, comboSeconds: 9, capRatio: 0.8 },
  { id: 'armor_champion', name: '覇者の鎧', price: 200000, comboStep: 65, comboSeconds: 12, capRatio: 0.9 },
  { id: 'armor_rico', name: 'リコの鎧', price: 10000000, comboStep: 80, comboSeconds: 2, capRatio: 0.9, rico: true },
];

const RING_CATALOG = [
  { id: 'ring_copper', name: '銅の指輪', price: 1500, rareChanceBonus: 0.01 },
  { id: 'ring_silver', name: '銀の指輪', price: 6000, rareChanceBonus: 0.02 },
  { id: 'ring_gold', name: '金の指輪', price: 20000, rareChanceBonus: 0.03 },
  { id: 'ring_dragon_eye', name: '竜眼の指輪', price: 70000, rareChanceBonus: 0.05 },
  { id: 'ring_luck', name: '幸運の指輪', price: 220000, rareChanceBonus: 0.08 },
  { id: 'ring_rico', name: 'リコの指輪', price: 10000000, rareChanceBonus: 0.01, rico: true },
];

const TITLE_CONNECTIVES = [
  { id: 'conn_no', text: 'の' },
  { id: 'conn_ga', text: 'が' },
  { id: 'conn_na', text: 'な' },
  { id: 'conn_ppoi', text: 'っぽい' },
  { id: 'conn_kei', text: '系' },
  { id: 'conn_none', text: '' },
];

const LEGENDARY_TITLE_FRONTS = new Set(['最強', '世界最強', '伝説級', '選ばれし', '伝説']);

const TITLE_FRONT_NAMES = [
  '見習い', '新米', '一人前', '熟練', 'ベテラン', '天才', '凡人', '残念', '幸運', '不運',
  '天然', 'おっちょこちょい', '高身長', '小柄', '眠そう', 'お腹ペコペコ',
  'ナイスバディー', '毛むくじゃら', '筋肉モリモリ',
  '最強', '世界最強', '伝説級', '選ばれし', '伝説',
];

const TITLE_FRONT_CATALOG = TITLE_FRONT_NAMES.map((name) => ({
  id: `tf_${name}`,
  name,
  price: LEGENDARY_TITLE_FRONTS.has(name) ? 5000 : 500,
}));

const TITLE_BASE_NOUNS = [
  '村人', '旅人', '農夫', '漁師', '猟師',
  '商人', '鍛冶屋', '薬師', '吟遊詩人', '料理人',
  '執事', '門番', '兵士', '盗賊', '傭兵',
  '占い師', '詩人', '冒険者', '戦士', '弓使い',
  '剣士', '槍使い', '拳闘士', '魔法使い', '僧侶',
  '神官', '錬金術師', '召喚士', '探検家', '忍者',
  '侍', '海賊', '狩人', '竜使い', '守護者',
  '賢者', '大魔導士', '聖騎士', '竜騎士', '騎士',
  '王', '女王', '勇者', '英雄',
];

const TITLE_BACK_CATALOG = TITLE_BASE_NOUNS.map((name) => ({ id: `tb_${name}`, name, price: 5000 }));

const ITEM_CATALOG = [
  { id: 'item_happy_grass', name: 'しあわせ草', price: 10000, effect: 'exp', value: 100, stackable: false, hasShopStock: true },
  { id: 'item_fairy_dust', name: '妖精の粉', price: 5000, effect: 'rare_chance_next_game', value: 0.10, stackable: true, maxStack: 99 },
  { id: 'item_heart_vessel', name: 'ハートの器', price: 100000, effect: 'heart_cap_up', value: 999, stackable: false, requiresDiscipleStreak: 1000 },
  { id: 'item_reincarnation_necklace', name: '輪廻のネックレス', price: 50000, effect: 'unlock_eternal_combo', stackable: false, requiresPrestige: 1 },
  { id: 'item_mechanical_egg', name: '機械仕掛けの卵', price: 1000000000, effect: 'easter_egg_dev_contact', stackable: false },
];

const ICON_CATALOG = {
  free: ['🗡️', '⚔️', '🏹', '🔥', '❄️', '⭐', '👑', '🐉', '🦊', '🐱', '🧙', '🛡️'],
  shop: [
    { id: 'icon_trophy', icon: '🏆', price: 1500 },
    { id: 'icon_target', icon: '🎯', price: 1500 },
    { id: 'icon_moon', icon: '🌙', price: 1500 },
    { id: 'icon_sun', icon: '☀️', price: 1500 },
    { id: 'icon_wave', icon: '🌊', price: 1500 },
    { id: 'icon_clover', icon: '🍀', price: 1500 },
    { id: 'icon_gem', icon: '💎', price: 1500 },
    { id: 'icon_owl', icon: '🦉', price: 1500 },
    { id: 'icon_ghost', icon: '👻', price: 1500 },
    { id: 'icon_dolphin', icon: '🐬', price: 1500 },
    { id: 'icon_mask', icon: '🎭', price: 1500 },
    { id: 'icon_lion', icon: '🦁', price: 1500 },
    { id: 'icon_wolf', icon: '🐺', price: 1500 },
    { id: 'icon_jar', icon: '🏺', price: 1500 },
    { id: 'icon_spider', icon: '🕷️', price: 1500 },
    { id: 'icon_bolt', icon: '⚡', price: 1500 },
    { id: 'icon_scorpion', icon: '🦂', price: 1500 },
    { id: 'icon_elf', icon: '🧝', price: 1500 },
    { id: 'icon_vampire', icon: '🧛', price: 1500 },
    { id: 'icon_rainbow', icon: '🌈', price: 1500 },
    { id: 'icon_eagle', icon: '🦅', price: 1500 },
    { id: 'icon_skull', icon: '💀', price: 1500 },
    { id: 'icon_tiger', icon: '🐯', price: 1500 },
    { id: 'icon_star2', icon: '🌟', price: 1500 },
    { id: 'icon_orb', icon: '🔮', price: 1500 },
    { id: 'icon_trident', icon: '🔱', price: 1500 },
    { id: 'icon_otherdragon', icon: '🐲', price: 1500 },
    { id: 'icon_moai', icon: '🗿', price: 1500 },
    { id: 'icon_unicorn', icon: '🦄', price: 1500 },
  ],
};

const BGM_CATALOG = [
  {
    id: 'bgm_default',
    name: '通常のBGM（ダンジョンごとの自動生成）',
    price: 0,
  },
  {
    id: 'bgm_shamisen',
    name: 'しゃみせん',
    price: 1000000,
    file: 'BGM/しゃみせん.mp3',
  },
  {
    id: 'bgm_pop_music',
    name: 'ぽっぷみゅーじっく',
    price: 1000000,
    file: 'BGM/ぽっぷみゅーじっく.mp3',
  },
  {
    id: 'bgm_kawaime_battle',
    name: 'かわいめバトル',
    price: 1000000,
    file: 'BGM/かわいめバトル.mp3',
  },
];
